# Generated by Django 3.2.13 on 2022-07-07 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=70)),
                ('Course_Fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usermember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tr_Address', models.CharField(max_length=200)),
                ('Tr_Age', models.IntegerField()),
                ('Tr_gender', models.CharField(max_length=10)),
                ('Tr_image', models.ImageField(upload_to='image/')),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursemodel')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_Name', models.CharField(max_length=100)),
                ('Stud_Address', models.CharField(max_length=200)),
                ('Stud_Age', models.IntegerField()),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.coursemodel')),
            ],
        ),
    ]
